import Capacitor
import UIKit

/// Exists solely to register the app's own plugins.
///
/// Measured rather than assumed: with `ShazamPlugin` compiling into the app
/// target and nothing else done, the bridge exposed only
/// `["CapacitorHttp","Console","WebView","CapacitorCookies","SystemBars"]` and
/// `Capacitor.isPluginAvailable("Shazam")` answered false. Capacitor 8 builds
/// its plugin list from the Swift packages the CLI writes into
/// `CapApp-SPM/Package.swift`, which is regenerated by `cap sync` and carries a
/// DO NOT MODIFY banner - so a plugin that lives in the app rather than in a
/// node_modules package has to say so here.
///
/// `capacitorDidLoad` is the hook that runs after the bridge exists and before
/// the web view loads, which is the only window where a registration is early
/// enough for the page to see it.
class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginInstance(ShazamPlugin())
        bridge?.registerPluginInstance(AppleMusicPlugin())
    }
}
